<div style="margin-left: 20px; margin-right: 30px;">
    <table class="table  table-borderless" id="tableCkpn">
        <thead class="secondary-color text-center">
            <tr>
                <th style="text-align: left; background-color: #F7F7FC;">No.</th>
                <th style="text-align: left; background-color: #F7F7FC;">No Account</th>
                <th style="text-align: left; background-color: #F7F7FC;">Account Name</th>
                <th style="text-align: left; background-color: #F7F7FC;">CIF</th>
                <th style="text-align: left;background-color: #F7F7FC;">Kantor Sales</th>
                <th style="text-align: left;background-color: #F7F7FC;">Provinsi</th>
                <th style="text-align: left;background-color: #F7F7FC;">Category Name 1</th>
                <th style="text-align: left;background-color: #F7F7FC;">Category Name 2</th>
                <th style="text-align: left;background-color: #F7F7FC;">Category</th>
                <th style="text-align: left;background-color: #F7F7FC;">Kode Kantor</th>
                <th style="text-align: left;background-color: #F7F7FC;">Wilayah 1</th>
                <th style="text-align: left;background-color: #F7F7FC;">Wilayah 2</th>
                <th style="text-align: left;background-color: #F7F7FC;">Segmen</th>
                <th style="text-align: left;background-color: #F7F7FC;">LPDC</th>
                <th style="text-align: left;background-color: #F7F7FC;">THLPDC</th>
                <th style="text-align: left;background-color: #F7F7FC;">Modifikasian</th>
                <th style="text-align: left;background-color: #F7F7FC;">Restru</th>
                <th style="text-align: left;background-color: #F7F7FC;">Hari Tunggak Norek</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket Tunggak Norek</th>
                <th style="text-align: left;background-color: #F7F7FC;">Haritung CIF</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket Tunggak CIF</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket Pakai</th>
                <th style="text-align: left;background-color: #F7F7FC;">Stage</th>
                <th style="text-align: left;background-color: #F7F7FC;">Y CALC</th>
                <th style="text-align: left;background-color: #F7F7FC;">Amount Type</th>
                <th style="text-align: left;background-color: #F7F7FC;">EIR</th>
                <th style="text-align: left;background-color: #F7F7FC;">FLAT RATE</th>
                <th style="text-align: left;background-color: #F7F7FC;">TYPE RATE</th>
                <th style="text-align: left;background-color: #F7F7FC;">OS POKOK</th>
                <th style="text-align: left;background-color: #F7F7FC;">Angsuran Bunga Tertunggak</th>
                <th style="text-align: left;background-color: #F7F7FC;">OS POKOK 2</th>
                <th style="text-align: left;background-color: #F7F7FC;">OS Bunga</th>
                <th style="text-align: left;background-color: #F7F7FC;">OS AR</th>
                <th style="text-align: left;background-color: #F7F7FC;">Pokok Pinjaman</th>
                <th style="text-align: left;background-color: #F7F7FC;">Total AR Awal</th>
                <th style="text-align: left;background-color: #F7F7FC;">Tgl AR</th>
                <th style="text-align: left;background-color: #F7F7FC;">Maturity Date</th>
                <th style="text-align: left;background-color: #F7F7FC;">Tenor</th>
                <th style="text-align: left;background-color: #F7F7FC;">EIR Calc</th>
                <th style="text-align: left;background-color: #F7F7FC;">EAD</th>
                <th style="text-align: left;background-color: #F7F7FC;">Tenor Sisa</th>
                <th style="text-align: left;background-color: #F7F7FC;">Tenor Sisa Y</th>
                <th style="text-align: left;background-color: #F7F7FC;">Tenor Sisa By Maturity Date</th>
                <th style="text-align: left;background-color: #F7F7FC;">Tenor Y By Maturity Date</th>
                <th style="text-align: left;background-color: #F7F7FC;">Stage Mdf</th>
                <th style="text-align: left;background-color: #F7F7FC;">Y Calc</th>
                <th style="text-align: left;background-color: #F7F7FC;">Amount Type</th>
                <th style="text-align: left;background-color: #F7F7FC;">PD BS</th>
                <th style="text-align: left;background-color: #F7F7FC;">PD US</th>
                <th style="text-align: left;background-color: #F7F7FC;">LGD</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket Pakai PE</th>
                <th style="text-align: left;background-color: #F7F7FC;">PE %</th>
                <th style="text-align: left;background-color: #F7F7FC;">PE Nominal</th>
                <th style="text-align: left;background-color: #F7F7FC;">Angsuran Bunga Tertunggak</th>
                <th style="text-align: left;background-color: #F7F7FC;">Angsuran Bunga Tertunggak PV</th>
                <th style="text-align: left;background-color: #F7F7FC;">EAD : GCA & NCA</th>
                <th style="text-align: left;background-color: #F7F7FC;">ECL Bottomside</th>
                <th style="text-align: left;background-color: #F7F7FC;">ECL Bottomside PV</th>
                <th style="text-align: left;background-color: #F7F7FC;">% ECL BL</th>
                <th style="text-align: left;background-color: #F7F7FC;">ECL Upside</th>
                <th style="text-align: left;background-color: #F7F7FC;">ECL Upside PV</th>
                <th style="text-align: left;background-color: #F7F7FC;">% ECL US</th>
                <th style="text-align: left;background-color: #F7F7FC;">ECL FIX</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket OJK</th>
                <th style="text-align: left;background-color: #F7F7FC;">Jenis Pembiayaan</th>
                <th style="text-align: left;background-color: #F7F7FC;">Cust Type</th>
                <th style="text-align: left;background-color: #F7F7FC;">Pokok Pembiayaan Netto</th>
                <th style="text-align: left;background-color: #F7F7FC;">ECL Accounting</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket Per Cif</th>
                <th style="text-align: left;background-color: #F7F7FC;">Bucket Per Norek</th>
                <th style="text-align: left;background-color: #F7F7FC;">Collective/Individual</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $no = 1;
            // $query = mssql_query("exec buatLaporanCkpn '$thbl'");   
            $query = mssql_query("SELECT * FROM ckpn_ecl WHERE thbl='$thbl'");  
            while($data= mssql_fetch_assoc($query)){ ?>
            <tr>
            <td style="text-align: left;"><?php echo $no++; ?></td>
            <td style="text-align: left;"><?php echo $data['noAccount']; ?></td>
            <td style="text-align: left;"><?php echo $data['accountName']; ?></td>
            <td style="text-align: left;"><?php echo $data['cif']; ?></td>
            <td style="text-align: left;"><?php echo $data['kantorSales']; ?></td>
            <td style="text-align: left;"><?php echo $data['provinsi']; ?></td>
            <td style="text-align: left;"><?php echo $data['categoryName']; ?></td>
            <td style="text-align: left;"><?php echo $data['categoryName2']; ?></td>
            <td style="text-align: left;"><?php echo $data['category']; ?></td>
            <td style="text-align: left;"><?php echo $data['kodeKantor']; ?></td>
            <td style="text-align: left;"><?php echo $data['wilayah']; ?></td>
            <td style="text-align: left;"><?php echo $data['wilayah2']; ?></td>
            <td style="text-align: left;"><?php echo $data['segmen']; ?></td>
            <td style="text-align: left;"><?php echo $data['lpdc']; ?></td>
            <td style="text-align: left;"><?php echo $data['thLpdc']; ?></td>
            <td style="text-align: left;"><?php echo $data['modifikasian']; ?></td>
            <td style="text-align: left;"><?php echo $data['restru']; ?></td>
            <td style="text-align: left;"><?php echo $data['hariTunggakNorek']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketTunggakNorek']; ?></td>
            <td style="text-align: left;"><?php echo $data['haritungCif']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketTunggakCif']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketPakai']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketStage']; ?></td>
            <td style="text-align: left;"><?php echo $data['yCalc']; ?></td>
            <td style="text-align: left;"><?php echo $data['amountType']; ?></td>
            <td style="text-align: left;"><?php echo $data['eir']; ?></td>
            <td style="text-align: left;"><?php echo $data['flatRate']; ?></td>
            <td style="text-align: left;"><?php echo $data['typeRate']; ?></td>
            <td style="text-align: left;"><?php echo $data['osPokok']; ?></td>
            <td style="text-align: left;"><?php echo $data['angsuranBungaTunggak']; ?></td>
            <td style="text-align: left;"><?php echo $data['osPokok2']; ?></td>
            <td style="text-align: left;"><?php echo $data['osBunga']; ?></td>
            <td style="text-align: left;"><?php echo $data['osAr']; ?></td>
            <td style="text-align: left;"><?php echo $data['pokokPinjaman']; ?></td>
            <td style="text-align: left;"><?php echo $data['totalArAwal']; ?></td>
            <td style="text-align: left;"><?php echo $data['tglAr']; ?></td>
            <td style="text-align: left;"><?php echo $data['maturityDate']; ?></td>
            <td style="text-align: left;"><?php echo $data['tenor']; ?></td>
            <td style="text-align: left;"><?php echo $data['EIR2']; ?></td>
            <td style="text-align: left;"><?php echo $data['EAD']; ?></td>
            <td style="text-align: left;"><?php echo $data['sisaTenor']; ?></td>
            <td style="text-align: left;"><?php echo $data['tenorSisaY']; ?></td>
            <td style="text-align: left;"><?php echo $data['sisaTenorByM']; ?></td>
            <td style="text-align: left;"><?php echo $data['tenorYByMaturityDate']; ?></td>
            <td style="text-align: left;"><?php echo $data['stageModifikasian']; ?></td>
            <td style="text-align: left;"><?php echo $data['yCalc2']; ?></td>
            <td style="text-align: left;"><?php echo $data['amountType2']; ?></td>
            <td style="text-align: left;"><?php echo $data['RTL']; ?></td>
            <td style="text-align: left;"><?php echo $data['MAT']; ?></td>
            <td style="text-align: left;"><?php echo $data['LGD']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketPakaiPE']; ?></td>
            <td style="text-align: left;"><?php echo $data['PE']; ?></td>
            <td style="text-align: left;"><?php echo $data['peNominal']; ?></td>
            <td style="text-align: left;"><?php echo $data['angsuranBungaTunggak']; ?></td>
            <td style="text-align: left;"><?php echo $data['angsuranBungaTunggakPV']; ?></td>
            <td style="text-align: left;"><?php echo $data['ead_GcaNca']; ?></td>
            <td style="text-align: left;"><?php echo $data['eclBottomside']; ?></td>
            <td style="text-align: left;"><?php echo $data['eclBottomsidePv']; ?></td>
            <td style="text-align: left;"><?php echo $data['persenEclBl']; ?></td>
            <td style="text-align: left;"><?php echo $data['eclUpside']; ?></td>
            <td style="text-align: left;"><?php echo $data['eclUpsidePV']; ?></td>
            <td style="text-align: left;"><?php echo $data['persenEclUs']; ?></td>
            <td style="text-align: left;"><?php echo $data['eclFix']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketOjk']; ?></td>
            <td style="text-align: left;"><?php echo $data['jenisPembiayaan']; ?></td>
            <td style="text-align: left;"><?php echo $data['custType']; ?></td>
            <td style="text-align: left;"><?php echo $data['pokokPembiayaanNetto']; ?></td>
            <td style="text-align: left;"><?php echo $data['eclAcc']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketPerCif']; ?></td>
            <td style="text-align: left;"><?php echo $data['bucketPerNorek']; ?></td>
            <td style="text-align: left;"><?php echo $data['collIndi']; ?></td>
            </tr>
            <?php } ?>
    </tbody>
    <br>
</table>
</div>